### ISSUE TITLE
cant download forge 1.7.10

### ISSUE THREAD

**Issue by EldosHD** [ParadigmMC/mcman#34]
I encountered this while trying to install and build the [the lost era](https://modrinth.com/modpack/the-lost-era/version/1.6.4) modpack.
If you try to run a 1.7.10 forge installer, it uses a wrong download url during the build step. 
I get this error:
`Error: HTTP status client error (404 Not Found) for url (https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614/forge-1.7.10-10.13.4.1614-installer.jar)`

The actual url is: 
`https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar`
so a `-1.7.10` is missing.

**Comment by TheAlan404** [comment]
Forge's maven versioning isnt consistent :c ill see what i can do

**Comment by TheAlan404** [comment]
Fixed! Will release 0.4.1 with a few patches soon
