### ISSUE TITLE
Sleeping for 584542100000 years on rate limit

### ISSUE THREAD

**Issue by ClusterConsultant** [ParadigmMC/mcman#36]
When getting rate limited, mcman seems to pick a very very large number of seconds to sleep.  While I can work around this by just using a token, it seems this is not ideal behavior.
![image](https://github.com/ParadigmMC/mcman/assets/19409904/4f04e293-1c1f-4bc0-b0e5-f3d8f11cc5c6)

**Comment by TheAlan404** [comment]
wow um. that number is decided upon the `X-Ratelimit-Reset` header value sent back by modrinth, ill take a look at it

**Comment by TheAlan404** [comment]
> X-Ratelimit-Reset: the time in seconds until the ratelimit window resets

yep, should be easy to fix
