### ISSUE TITLE
Error with older versions of a vanilla minecraft server (tested with 1.12.2)

### ISSUE THREAD

**Issue by MrPixelized** [ParadigmMC/mcman#39]
Trying to use a `type = "vanilla"` `[jar]` section with `mc_version = "1.12.2"` leads to the following error on running `mcman build`:

```
Error: Resolving Vanilla

Caused by:
    0: error decoding response body: missing field `name` at line 1 column 11698
    1: missing field `name` at line 1 column 11698
```

I've gotten around this by instead using:

```
[jar]
type = "url"
url = "https://piston-data.mojang.com/v1/objects/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar"
```

Which works, but also means that I have to manually edit the EULA file before starting the server.

It's nice that the system is flexible enough to support this fix, but the whole situation leads to two things:

- This bug report (of the issue with vanilla servers)
- A feature request: custom build hooks (I could add a hook that simply performs `echo "eula=true" > eula.txt`

**Comment by TheAlan404** [comment]
Oh, I think I know how to fix this. Expect it fixed in `0.4.3`

About the build hooks - I was already planning on something like this but a massive issue with it is platform independency - Windows and Linux shells are greatly different...

**Comment by TheAlan404** [comment]
Hold on a second, why didn't you put an `eula.txt` under the `config` directory? It'll get copied to `server`?

**Comment by MrPixelized** [comment]
I just didn't think of it! But regardless, these build hooks would be quite nice. I think platform independency isn't that hard, just execute a file directly. On linux, the desired program (whether it be shell language or anything else) can be set using the shebang, and on windows you can use links or binaries.

**Comment by TheAlan404** [comment]
How would the config for that work? Could you provide any examples if you can think of any? Thanks!

**Comment by MrPixelized** [comment]
#40
