### ISSUE TITLE
Test server start detection breaks with better log4j config mod

### ISSUE THREAD

**Issue by maximumpower55** [ParadigmMC/mcman#46]
https://github.com/ParadigmMC/mcman/blob/c6c7168081f7b735c77d241f9ae30329e85d396b/src/hot_reload/mod.rs#L228
I was having this weird issue with `mcman run --test` not ending the process after the server started, found out the mod <https://modrinth.com/mod/better-log4j-config> conflicts with this line since it changes how all logging looks. Easiest solution would probably just to add another case to this line

**Comment by TheAlan404** [comment]
i think im just going to add a new field in `server.toml` so you can customize the success message, this should allow more flexibility

**Comment by maximumpower55** [comment]
Sounds good, I'll close this now since I saw it was added into code
