### ISSUE TITLE
`mcman build` skips changing `server.properties` if `.mcman.lock` is present.

### ISSUE THREAD

**Issue by EldosHD** [ParadigmMC/mcman#51]
If you change the `PORT` in `server.toml` and run `mcman build`, it wont update an already existing `server/server.properties` file if `.mcman.lock` is present.

**Comment by TheAlan404** [comment]
oh right because the current logic checks for the last modified file timestamp 🤦‍♀️

**Comment by TheAlan404** [comment]
0.4.4 will contain a hotfix for this
