### ISSUE TITLE
Can't download datapack mods

### ISSUE THREAD

**Issue by PotatoPresident** [ParadigmMC/mcman#9]
Datapack projects can have mod versions ex: https://modrinth.com/datapack/tectonic

Also maybe just support for datapacks as a whole

**Comment by TheAlan404** [comment]
oh ok this is definitely an oversight on my part, ill look into it, thanks!

**Comment by TheAlan404** [comment]
Commit https://github.com/ParadigmMC/mcman/commit/28997cc3a9690f287068ec2820bdef963c598798 should allow you to import the mods from the datapack project links now.

I'll also add some sort of datapacks feature too, but I'm conflicted on how I should do it... i'm thinking of something like

```toml
[[worlds.smp.datapacks]]
type = "modrinth"
id = "tectonic"
# version ...
```

which essentially would download the `Downloadable` into `server/{world_name}/datapacks/`
